export const data = JSON.parse("{\"key\":\"v-4e141a4b\",\"path\":\"/dl4mt/2021/cpgmt/\",\"title\":\"Contextual Parameter Generation for Universal Neural Machine Translation\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Contextual Parameter Generation for Universal Neural Machine Translation\",\"author\":\"Bairu Hou\",\"date\":\"2021-11-28T00:00:00.000Z\",\"tag\":[\"Multilingual MT\"],\"category\":[\"MT\",\"DL4MT\"],\"summary\":\"Introduction A typical neural machine translation (NMT) system needs to support the translation among various languages, that is, a multilingual(many-to-many) NMT system rather tha\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://lileicc.github.io/blog/dl4mt/2021/cpgmt/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MLNLP Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Contextual Parameter Generation for Universal Neural Machine Translation\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://lileicc.github.io/blog/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Contextual Parameter Generation for Universal Neural Machine Translation\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Bairu Hou\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Multilingual MT\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-11-28T00:00:00.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"Introduction\",\"slug\":\"introduction\",\"link\":\"#introduction\",\"children\":[]},{\"level\":2,\"title\":\"Preliminary\",\"slug\":\"preliminary\",\"link\":\"#preliminary\",\"children\":[]},{\"level\":2,\"title\":\"Core Idea: Contextual Parameter Generator\",\"slug\":\"core-idea-contextual-parameter-generator\",\"link\":\"#core-idea-contextual-parameter-generator\",\"children\":[]},{\"level\":2,\"title\":\"Dive deeper: the design of CPG\",\"slug\":\"dive-deeper-the-design-of-cpg\",\"link\":\"#dive-deeper-the-design-of-cpg\",\"children\":[]},{\"level\":2,\"title\":\"Experiment and Performance\",\"slug\":\"experiment-and-performance\",\"link\":\"#experiment-and-performance\",\"children\":[]},{\"level\":2,\"title\":\"Language embeddings\",\"slug\":\"language-embeddings\",\"link\":\"#language-embeddings\",\"children\":[]},{\"level\":2,\"title\":\"Summary\",\"slug\":\"summary\",\"link\":\"#summary\",\"children\":[]},{\"level\":2,\"title\":\"Reference\",\"slug\":\"reference\",\"link\":\"#reference\",\"children\":[]}],\"readingTime\":{\"minutes\":6.52,\"words\":1955},\"filePathRelative\":\"dl4mt/2021/cpgmt/README.md\",\"localizedDate\":\"November 27, 2021\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
